{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_verify", "time": 0.21572470664978027, "type": "failure", "errtype": "builtins.AssertionError", "message": "False is not true", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pb-tester-ccdle12/signing-and-verification-jsong-pb-sf-072618/test/index_test.py\", line 13, in test_verify\n    self.assertTrue(point.verify(z, Signature(r, s)))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\nAssertionError: False is not true\n"}]}